GoSmartValue.Web/Areas/user/Controllers/ValuationsController.cs
using AutoMapper;
using AV.Common.Entities;
using AV.Contracts.Enums;
using AV.Contracts.Models.Payment.Requests;
using AV.Contracts.Models.Product;
using AV.Contracts.Models.Product.Requests;
using AV.Contracts.Models.Valuation;
using AV.Contracts.Services;
using GoSmartValue.Web.Controllers;
using GoSmartValue.Web.Services;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using User = AV.Common.Entities.User;

namespace GoSmartValue.Web.Areas.user.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Area("user")]
    [Route("[controller]/")]
    public class ValuationsController : SecureController
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IDocumentStoreService _documentStoreService;
        private readonly IValuationsService _valuationsService;
        private readonly IInstructionService _instructionService;
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public ValuationsController(
            UserManager<User> userManager,
            RoleManager<Role> roleManager,
            SignInManager<User> signInManager,
            IDocumentStoreService documentStoreService,
            IValuationsService valuationsService,
            IInstructionService instructionService,
            IUserManagerService userService,
            IMediator mediator,
            IMapper mapper)
            : base(userManager, roleManager, userService, mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _documentStoreService = documentStoreService;
            _valuationsService = valuationsService;
            _instructionService = instructionService;
            _mediator = mediator;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("GetValuation")]
        [AllowAnonymous]
        public IActionResult GetValuation()
        {
            return View("ValuationRequest");
        }

        [HttpPost("GetValuation")]
        [AllowAnonymous]
        public async Task<IActionResult> GetValuation(ComparableRequestViewModel comparableRequestRequest)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("Missing data", "Please ensure all fields are filled in correctly.");
                return View("ValuationRequest", comparableRequestRequest);
            }

            AddHttpRequestDate(comparableRequestRequest);
            var result = (await _valuationsService.CalculateValuation(comparableRequestRequest)).Item1;
            return RedirectToAction("ValuationResult", result);
        }

        [HttpGet]
        [Route("request")]
        public IActionResult ValuationResult(ComparableResultViewModel comparableResult)
        {
            ResetReturnUrl();
            return View(comparableResult);
        }

        [HttpGet]
        [Route("getreport")]
        public async Task<IActionResult> FullReportRequestGet(Guid id)
        {
            var comparableResult = await _valuationsService.GetComparableResult(id);
            comparableResult.ComparableResultId = id;
            return View(comparableResult);
        }

        [HttpGet]
        [Route("pay")]
        public async Task<IActionResult> InstantReportPayment(Guid id)
        {
            var user = CurrentUser;
            var request = await CreateMakePaymentRequest(user, id);
            return RedirectToAction("Payment", "Payment", request);
        }

        [HttpGet]
        [Route("getdetailedreport")]
        public async Task<IActionResult> IssueInstruction(Guid? id = null)
        {
            var instruction = new InstructionModel();
            if (id.HasValue)
            {
                instruction = ConvertToInstruction(await _valuationsService.GetComparableResult(id.Value));
            }
            return View(instruction);
        }

        [HttpPost]
        [Route("getdetailedreport")]
        public async Task<IActionResult> IssueInstruction(InstructionModel instruction, ICollection<IFormFile> UploadDocument = null)
        {
            if (ModelState.IsValid)
            {

                instruction.SupportingDocuments = _documentStoreService.ConvertToInstructionDocument<InstructionDocumentModel>(UploadDocument).ToList();
                instruction.IssuerId = CurrentUser.Id;
                await _instructionService.CreateInstruction(instruction);

                return RedirectToAction("InstructionSent", "Standard");
            }

            return View("IssueInstruction", instruction);
        }

        private async Task<ICollection<DocumentModel>> ExtractDocument(ICollection<IFormFile> documents)
        {
            return await _documentStoreService.SaveFiles(documents);
        }

        [HttpPost]
        [Route("request")]
        public async Task<IActionResult> FullReportRequestPost(ComparableResultViewModel comparableResult)
        {
            if (!ModelState.IsValid)
            {
                return View("ValuationResult", comparableResult);
            }

            if (_signInManager.IsSignedIn(User))
            {
                comparableResult.RequesterUserId = CurrentUser.Id;
            }

            _valuationsService.RequestFullReport(comparableResult);

            return Redirect(await ResolveUserRedirectUrl());
            // return RedirectToAction("Paypal","Home", new {product = comparableResult.ReportType});
        }

        private InstructionModel ConvertToInstruction(ComparableResultViewModel comparableResult)
        {
            return new InstructionModel
            {
                IssuerId = CurrentUser.Id,
                Issuer = _mapper.Map<AV.Contracts.Models.Users.UserModel>(CurrentUser),
                LocationId = comparableResult.Comparable.LocationId,
                Location = comparableResult.Comparable.Location,
                LocalityId = comparableResult.Comparable.LocalityId,
                Locality = comparableResult.Comparable.Locality,
                PlotNumber = comparableResult.Comparable.PlotNo,
            };
        }

        private void AddHttpRequestDate(ComparableRequestViewModel comparableRequestRequest)
        {
            comparableRequestRequest.RequestDate = DateTime.UtcNow;
            comparableRequestRequest.RequestUri = Request.GetDisplayUrl();
            comparableRequestRequest.Host = Request.Host.Host;
        }
        private async Task<MakePaymentRequest> CreateMakePaymentRequest(User user, Guid id)
        {
            var product = await GetProductPrice(PaymentType.InstantReport.ToString());
            return new MakePaymentRequest
            {
                InitiatedByUserId = user.Id,

                Reference = id.ToString(),
                Type = PaymentType.InstantReport,
                Amount = (int)product.Price,
                ServiceName = product.Description,
                ServiceType = product.ServiceType
            };
        }

        private async Task<ProductModel> GetProductPrice(string productName)
        {
            return await _mediator.Send(new GetProductDetailsRequest
            {
                Name = productName,
            });
        }
    }
}

GoSmartValue.Web/Areas/user/Views/Valuations/Index.cshtml
@using GoSmartValue.Web.Services
@model ICollection<AV.Contracts.Models.Valuation.ComparableResultViewModel>
@inject CachedStorageService CachedStorageService

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>My Property Valuation Estimates</h1>
<table class="table table-striped">
    <thead>
    <tr>
        <th cope="col">
            Reference No:
        </th>
        <th cope="col">
            Estimated value:
        </th>
        <th cope="col">
            Estimated On:
        </th>
        <th cope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var comparable in Model)
    {
        <tr>
            <th scope="row">
                @Html.DisplayFor(modelItem => comparable.ReferenceNumber)
            </th>
            <td>
                @Html.DisplayFor(modelItem => $"{comparable.EstimatedValue:C}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => $"{comparable.EstimatedOn:d}")
            </td>
            <td>
                @Html.ActionLink("Request Report", "FullReportRequest", "Valuations", new { comparableId = comparable.ReferenceNumber }, htmlAttributes: new { @class = "btn btn-success" })|
                @Html.ActionLink("Delete", "Delete", "Valuations", new { Id = comparable.ReferenceNumber }, htmlAttributes: new { @class = "btn btn-primary" })|
            </td>
        </tr>
        @if (comparable.PropertySaleDetail != null)
        {
            <tr>
                <td colspan="4">
                    <div>
                        <h3>Property Summary</h3>
                        <p>
                            Plot No: @comparable.PropertySaleDetail.PlotNo | @CachedStorageService.Cities[@comparable.PropertySaleDetail.LocationId]
                        </p>
                    </div>
                </td>
            </tr>
        }
    }
    </tbody>
</table>

GoSmartValue.Web/Areas/user/Views/Valuations/IssueInstruction.cshtml
@using AV.Contracts.Enums
@using GoSmartValue.Web.Services
@model AV.Contracts.Models.Valuation.InstructionModel
@inject CachedStorageService CachedStorageService

@{
    var defaultLocation = 33;
    var locations = new SelectList(
        CachedStorageService.Cities
            .Select(c =>
                new SelectListItem { Text = c.Value, Value = c.Key.ToString(), Selected = c.Key == defaultLocation })
        , "Value", "Text", defaultLocation);

    var localities = CachedStorageService.GetLocalities(defaultLocation);

    var valuers = new SelectList(
        CachedStorageService.GetValuers().Result
            .Select(c =>
                new SelectListItem { Text = c.FullName, Value = c.Id.ToString() })
        , "Value", "Text", "-");
}
@{
    ViewData["Title"] = "Instruct";

    Layout = "_Layout";
}
<link href="~/lib/jquery-ui/jquery.timepicker.min.css" />
<div class="outer container-fluid image-container set-full-height" style="background-image:url(/valuerHome.jpg);">
    <div class="middle" style="padding-top: 60px">
        <div class="inner">
            <form method="post" enctype="multipart/form-data" style="background-color:transparent!important">
                <div class="container-fluid">
                    <div class="row form-group">
                        <div class="col-sm-4 shadow " style="background-color: #fff; min-height: 100px; padding: 10px;">
                            <div class="autocomplete label-floating form-group">
                                <label class="control-label">Location:city/town</label>
                                <input type="text" asp-for="LocationName" value="@Model.Location?.Name" tabindex="1"
                                       required="required" class="form-control" autocomplete="off" />
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-3 shadow" style="background-color: #fff; height: 100px; padding: 10px;">
                            <div class="form-group label-floating autocomplete">
                                <label class="control-label">Ward</label>
                                <input type="text" asp-for="LocalityName" value="@Model.Locality?.Name" tabindex="2" autocomplete="off"
                                       onfocus="SetLocalities()"
                                       class="form-control" />
                                <span asp-validation-for="LocalityName" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-3 shadow" style="background-color: #fff; height: 100px; padding: 10px;">
                            <div class="form-group label-floating col-sm-12">
                                <label class="control-label">Plot Number</label>
                                <input type="text" asp-for="PlotNumber" value="@Model.PlotNumber" tabindex="3" class="form-control" />
                            </div>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-sm-4 shadow" style="background-color: #fff; min-height: 100px; padding: 10px;">
                            <label>Select Valuer/Company</label>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="ValuerTypeOption">
                                <label class="custom-control-label" for="ValuerTypeOption">Select company</label>
                            </div>
                            <div id="ValuerOption">
                                <label class=" col-sm-12">Authorize Valuer</label>
                                <div class="col-sm-12">
                                    <select asp-for="ValuerId" tabindex="4" class="col-sm-12 form-control autocomplete">
                                        @foreach (var valuer in valuers)
                                        {
                                            <option value="@valuer.Value">@valuer.Text</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div id="OrganisationOption">
                                <label class=" col-sm-12">Organisations</label>
                                <div class="col-sm-12">
                                    <select asp-for="ValuerAccountId" tabindex="4" class="col-sm-12 form-control autocomplete">
                                        @foreach (var valuer in CachedStorageService.GetAccounts(AccountType.Valuer))
                                        {
                                            <option value="@valuer.Id">@valuer.CompanyName</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                        <div class="row col-sm-7 shadow p-2" style="background-color: #fff; min-height: 150px; ">
                            <label class="row col-sm-12">Supporting documents: <span style="color:red">File size limit is 2MB on each upload.Accepted file types:.pdf.jpeg.png</span></label>
                            <div class="col-sm-6">
                                <div class="row form-group">
                                    <div class="custom-file">
                                        <input type="file" id="UploadDocument" name="UploadDocument">
                                        <label class="custom-file-label">Upload document 1</label>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="custom-file">
                                        <input type="file" id="UploadDocument3" name="UploadDocument">
                                        <label class="custom-file-label">Upload document 3</label>
                                    </div>
                                </div>

                            </div>
                            <div class="col-sm-6">
                                <div class="row form-group">
                                    <div class="custom-file">
                                        <input type="file" id="UploadDocument2" name="UploadDocument">
                                        <label class="custom-file-label">Upload document 2</label>
                                    </div>

                                </div>
                                <div class="row form-group">
                                    <div class="custom-file">
                                        <input type="file" id="UploadDocument4" name="UploadDocument">
                                        <label class="custom-file-label">Upload document 4</label>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row  form-group">
                        <div class="col-sm-4 shadow p-2" style="background-color: #fff; min-height: 150px; padding: 10px; ">
                            <div class="col-sm-12">
                                <label class="col-sm-12">Access Information</label>
                                <div class="form-group label-floating ">
                                    <label class="control-label">Client Name</label>
                                    <input type="text" asp-for="ClientName" tabindex="6" required="required" class="form-control" />
                                </div>
                                <div class="form-group label-floating">
                                    <label class="control-label">Cell Number</label>
                                    <input type="text" asp-for="ClientMobileNumber" tabindex="7" required="required" class="form-control" />
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-1"></div>
                        <div class=" col-sm-3 shadow" style="background-color: #fff; min-height: 150px; padding: 10px;">
                            <div class="col-sm-12">
                                <label class="col-sm-12">Preferred access date</label>
                                <div class="col-sm-12">

                                    <input type="datetime-local" class="form-control" tabindex="8" asp-for="PreferredAccessDate" required="required">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1"></div>

                        <div class="col-sm-3 shadow" style="background-color: #fff; min-height: 150px; padding: 10px;">
                            <div class="row p-2">
                                <div class="form-group label-floating col-sm-12">
                                    <label class="control-label">Whatsapp Number</label>
                                    <input type="text" asp-for="WhatsAppNumber" tabindex="3" class="form-control" />
                                </div>
                                <div class="row col-sm-12">
                                    <span>Can you do a video walkthrough via Whatsapp? tick this if yes.</span>
                                </div>
                                <div class="row form-group col-sm-12">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" asp-for="isVideoWakthroughPossible" type="checkbox">
                                            Yes
                                            <span class="form-check-sign">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                    <div style="float: right">
                        <button asp-controller="Valuations" asp-action="IssueInstruction"
                                type="submit" class="btn btn-blue">
                            Issue Instruction
                        </button>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript" src="~/js/valuations.min.js"></script>
<script>
    $(document).ready(function () {
        $('#OrganisationOption').hide();

        $('#ValuerTypeOption').change(function () {
            if (this.checked !== true) {
                $('#OrganisationOption').hide();
                $('#ValuerOption').show();
            }
            else {

                $('#OrganisationOption').show();
                $('#ValuerOption').hide();
            }
        });
    });
</script>

GoSmartValue.Web/Areas/user/Views/Valuations/ValuationRequest.cshtml
@using AV.Contracts.Enums
@using GoSmartValue.Web.Services

@model AV.Contracts.Models.Valuation.ComparableRequestViewModel
@inject CachedStorageService CachedStorageService

@{
	Layout = "_Layout";

	SelectList locations = new SelectList(
		CachedStorageService.Cities
			.Select(c =>
				new SelectListItem { Text = c.Value, Value = c.Key.ToString(), Selected = c.Key == 33 })
		, "Value", "Text", "-");

	var localities = new List<SelectListItem>();

	var streets = new List<SelectListItem>();
}
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.0/dist/latest/bootstrap-autocomplete.min.js"></script>
<link href="~/css/bootstrap-datepicker.min.css" rel="stylesheet" />


<div id="QuickValuation" class="col-sm-12 image-container set-full-height" style="background-image:url(/discussions.jpg);">
	<div class="inner col-sm-12">
		<div id="ValuationRequest" name="ComparableRequest" class="row" style="padding:2.5rem">

			<div class="col-md-8 offset-md-2">
				<!--      Wizard container        -->
				<div class="wizard-container">
					<div class="card wizard-card" data-color="red" id="wizard">
						<form method="post">
							<!--        You can switch " data-color="blue" "  with one of the next bright colors: "green", "orange", "red", "purple"             -->
							<div class="wizard-header">
								<h3 class="wizard-title">
									Instant Valuation
								</h3>
								<h5>This information will help us calculate an estimate for you.</h5>
							</div>
							<div class="wizard-navigation">
								<ul>
									<li><a href="#propertyDetails" data-toggle="tab">Property Details</a></li>
									<li><a href="#situation" data-toggle="tab">Situation</a></li>
									@*<li><a href="#ownership" data-toggle="tab">Ownership</a></li>*@
								</ul>
							</div>
							<div class="tab-content">
								<div class="tab-pane" id="propertyDetails">
									<div class="row">
										<div class="col-sm-12">
											<h4 class="info-text"> Let's start with the basic details.</h4>
										</div>
										<div class="col-sm-6">
											<div class="autocomplete label-floating form-group">
												<label class="control-label">Location:city/town</label>
												<input type="text" asp-for="LocationName" autocomplete="off" tabindex="1"
													   required="required" class="form-control" />
											</div>
											<div class="form-group label-floating autocomplete">
												<label class="control-label">Street</label>
												<input type="text" asp-for="StreetName" autocomplete="off" tabindex="3"
													   onfocus="SetStreets()"
													   class="form-control" />
												<span asp-validation-for="StreetName" class="text-danger"></span>
                                            </div>
										</div>
										<div class="col-sm-6">
											<div class="form-group label-floating autocomplete">
												<label class="control-label">Ward</label>
												<input type="text" asp-for="LocalityName" autocomplete="off" tabindex="2"
													   onfocus="SetLocalities()"
													   class="form-control" />
												<span asp-validation-for="LocalityName" class="text-danger"></span>
											</div>
											<div class="form-group label-floating">
												<label class="control-label">Plot Number</label>
												<input asp-for="PlotNo" class="form-control" tabindex="4" />
												<span asp-validation-for="PlotNo" class="text-danger"></span>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="situation">
									<div class="row">
										<div class="col-sm-12"><h4 class="info-text">How big is your plot/property and what do you use it for? </h4></div>
										<div class="col-sm-6">
                                            <div class="label-floating form-group">
                                                <label class="control-label">Plot size</label>
                                                <input asp-for="Size" type="number" class="form-control" tabindex="5" />
                                                <span asp-validation-for="Size" class="text-danger"></span>
                                            </div>
                                            <div class="form-group label-floating">
                                                <label class="control-label">Developments</label>
                                                @Html.DropDownList("PropertyType",
                                                    new SelectList(CachedStorageService.GetDevelopments()),
                                                    new { @class = "form-control dropdown",@tabindex ="7" })
                                                <span asp-validation-for="PropertyType" class="text-danger"></span>
                                            </div>
										</div>
										<div class="col-sm-6">
                                            <div class="form-group label-floating">
                                                <label class="control-label">Plot measurement units</label>
                                                @Html.DropDownList("Metric",
                                                    new SelectList(Enum.GetValues(typeof(Metric))),
                                                    new { @class = "form-control dropdown",@tabindex ="6" })

                                            </div>
											<div class="form-group label-floating">
												<label class="control-label">Land Use</label>
												@Html.DropDownList("LandUse",
																			new SelectList(Enum.GetValues(typeof(LandUse))),
																			new { @class = "form-control dropdown",@tabindex ="8" })
												<span asp-validation-for="LandUse" class="text-danger"></span>
											</div>
										</div>

									</div>
								</div>
								@*<div class="tab-pane" id="ownership">
									<h4 class="info-text">Do you own this property?</h4>
									<div class="row">

											<div class="col-sm-6">
												<div class="autocomplete label-floating form-group">
													<label class="control-label">Purchase Date</label>
													<input asp-for="PurchaseDate" type="date" tabindex="9" class="form-control" />
													<span asp-validation-for="PurchaseDate" class="text-danger"></span>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group label-floating autocomplete">
													<label class="control-label">Purchase Price</label>
													<input type="number" name="PurchasePrice" id="PurchasePrice" tabindex="10"  class="form-control" />
													<span asp-validation-for="PurchasePrice" class="text-danger"></span>
												</div>
											</div>
										
									</div>
								</div>*@
							</div>
							<div class="container-fluid row wizard-footer">
								<div class="pull-left text-center col-sm-6">
									<input type='button' class='btn btn-previous btn-fill btn-black btn-wd' name='previous' value='Previous' />


								</div>
								<div class="pull-right text-center col-sm-6">
									<input type='button' class='btn btn-next btn-fill btn-blue btn-wd' name='next' value='Next' />
									<input type='submit' asp-area='user' asp-controller='Valuations' asp-action='GetValuation' class='btn btn-finish btn-fill btn-blue btn-wd' name='finish' value='Finish' />

								</div>
								<div class="clearfix"></div>
							</div>
						</form>
					</div>
				</div> <!-- wizard container -->
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="~/js/valuations.min.js"></script>
<script src="~/js/bootstrap-datepicker.min.js"></script>