GoSmartValue.Web/ViewModels/OrganisationViewModel.cs
using System;
using System.Collections.Generic;
using AV.Contracts.Models.Accounts;
using AV.Contracts.Models.Users;
using GoSmartValue.Web.Models;

namespace GoSmartValue.Web.ViewModels
{
    public class OrganisationViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string PostalAddress { get; set; }
        public string PhysicalAddress { get; set; }
        public int? LocationId { get; set; }
        public virtual LocationViewModel Location { get; set; }
        public int? LocalityId { get; set; }
        public virtual LocalityViewModel Locality { get; set; }
        public int? StreetId { get; set; }
        public string StreetName { get; set; }
        public string PlotNo { get; set; }
        public Guid PrimaryUserId { get; set; }
        public virtual UserModel PrimaryUser { get; set; }
        public ICollection<PhoneViewModel> PhoneNumbers { get; set; }
        public ICollection<AccountViewModel> UserAccounts { get; set; }
    }
}

GoSmartValue.Web/Areas/admin/Controllers/OrganisationController.cs
using System.Threading.Tasks;
using AutoMapper;
using AV.Common.Entities;
using GoSmartValue.Web.Controllers;
using GoSmartValue.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GoSmartValue.Web.Areas.admin.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Area("admin")]
    public class OrganisationController : SecureController
    {
        private readonly IUserManagerService _userManagerService;
        private readonly IMapper _mapper;
        private static string _viewsPath = "/areas/admin/Views/Organisation";
        private User _currentUser;

        public OrganisationController(IUserManagerService userManagerService, 
            UserManager<User> userManager, 
            RoleManager<Role> roleManager,
            IUserManagerService userService,
            IMapper mapper
            )
        : base(userManager, roleManager, userService, mapper)
        {
            _userManagerService = userManagerService;
            _mapper = mapper;
            _currentUser = userManagerService.GetUserDetails(User.Identity.Name);
        }

        [HttpGet]
        public ActionResult Index()
        {
            var organisations = _userManagerService.GetOrganistions(CurrentUser.Id);
            ViewBag.userId = CurrentUser.Id;
            return View($"{_viewsPath}/Index.cshtml", organisations);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View($"{_viewsPath}/Create.cshtml");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View($"{_viewsPath}/Create.cshtml");
        }

        // POST: Organisation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Edit");
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

GoSmartValue.Web/Areas/admin/Views/Organisation/Create.cshtml
@model GoSmartValue.Web.ViewModels.OrganisationViewModel

@{
    ViewBag.Title = "Create new Organisation";
    Layout = "_Layout";
}
<script src="~/js/bootstrap-select.js"></script>
<div class="row">
    <div class="col-md-12 align-content-center">
        <form method="post">
            <fieldset>
                <div class="card-title">
                    <center><h1>Create Organisation</h1></center>
                </div>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            </fieldset>
            <fieldset class="border p-2">
                <legend class="w-auto">Details</legend>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="Name">Organisation Name</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="PhoneNumbers">Main Phone Number</label>
                        <input asp-for="PhoneNumbers" class="form-control" />
                        <span asp-validation-for="PhoneNumbers" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="PostalAddress">Postal Address</label>
                    <input asp-for="PostalAddress" class="form-control" />
                    <span asp-validation-for="PostalAddress" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhysicalAddress">Physical Address</label>
                    <input asp-for="PhysicalAddress" type="text" class="form-control" />
                    <span asp-validation-for="PhysicalAddress" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PrimaryUser">Main Contact</label>
                    <input asp-for="PrimaryUser" type="text" class="form-control" />
                    <span asp-validation-for="PrimaryUser" class="text-danger"></span>
                </div>
            </fieldset>
            <fieldset class="border p-2">
                <button type="submit" class="btn btn-primary">Register</button>
            </fieldset>
        </form>
    </div>
</div>

GoSmartValue.Web/Areas/admin/Views/Organisation/Index.cshtml
@model IEnumerable<GoSmartValue.Web.ViewModels.OrganisationViewModel>

@{
    ViewData["Title"] = "Organisations";
    Layout = "_Layout";
}

<h1>Organisations</h1>

<p>
    @Html.ActionLink("Add","Create","Organisation",null,new {@class="btn btn-success"})
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th cope="col">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PhoneNumbers)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PostalAddress)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PrimaryUser)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.UserAccounts)
            </th>
            <th cope="col"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <th scope="row">
            @Html.DisplayFor(modelItem => item.Name)
            </th>
            <td>
                @foreach (var phone in item.PhoneNumbers)
                {
                    <i class="text-info"><span>Type: @phone.Type | @phone.PhoneNumber</span></i>
                }
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostalAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrimaryUser)
            </td>
            <td>
                <i class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Organisation" asp-action="Accounts">View Users</a>
                </i>
            </td>
            <td>
                @Html.ActionLink("Edit","Edit","Comparables", new {Id = @item.Id},htmlAttributes:new {@class="btn btn-success"})|
                @Html.ActionLink("Details","Details","Comparables", new {Id = @item.Id},htmlAttributes:new {@class="btn btn-primary"})|
                @Html.ActionLink("Delete","Delete","Comparables", new {Id = @item.Id},htmlAttributes:new {@class="btn btn-primary"})|
            </td>
        </tr>
}
    </tbody>
</table>