GoSmartValue.Web/Controllers/ValuerController.cs
using AutoMapper;
using AV.Common.Entities;
using AV.Contracts.Enums;
using AV.Contracts.Models;
using AV.Contracts.Models.Accounts.Commands;
using AV.Contracts.Models.Market.Requests;
using AV.Contracts.Models.Valuation;
using AV.Contracts.Services;
using GoSmartValue.Web.Models.GraphModels;
using GoSmartValue.Web.Services;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AuthorizeAttribute = Microsoft.AspNetCore.Authorization.AuthorizeAttribute;
using HttpGetAttribute = Microsoft.AspNetCore.Mvc.HttpGetAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;
using User = AV.Common.Entities.User;

namespace GoSmartValue.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize(Policy = Constants.AccessPolicies.Valuer)]
    public class ValuerController : SecureController
    {
        private readonly IDocumentStoreService _documentStoreService;
        private IValuationsService _valuationsService;
        private readonly IMarketInformationService _marketInformationService;
        private readonly IInstructionService _instructionService;
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        private readonly ILogger _logger;

        public ValuerController(
            UserManager<User> userManager,
            RoleManager<Role> roleManager,
            IDocumentStoreService documentStoreService,
            IValuationsService valuationsService,
            IMarketInformationService marketInformationService,
            IInstructionService instructionService,
            IUserManagerService usersService,
            IMediator mediator,
            IMapper mapper
        )
            : base(userManager, roleManager, usersService, mapper)
        {
            _documentStoreService = documentStoreService;
            _valuationsService = valuationsService;
            _marketInformationService = marketInformationService;
            _instructionService = instructionService;
            _mediator = mediator;
            _mapper = mapper;
            _logger = new LoggerFactory().CreateLogger(typeof(ValuerController));
        }

        public Task<User> GetCurrentUserAsync() => UserManager.GetUserAsync(HttpContext.User);

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult NewInstructions()
        {
            var instructions = _instructionService
                .GetInstructions(CurrentUser,
                    new List<InstructionStatus> { InstructionStatus.New, InstructionStatus.Pending });
            return View(instructions.OrderByDescending(i => i.CreatedDate));
        }

        [HttpGet]
        public IActionResult Pending()
        {
            var instructions = _instructionService
                .GetInstructions(CurrentUser,
                    new List<InstructionStatus> { InstructionStatus.Confirmed, InstructionStatus.Processing });
            return View(instructions.OrderByDescending(i => i.CreatedDate));
        }

        [HttpGet]
        public IActionResult CompleteInstructions()
        {
            var instructions = _instructionService
                .GetInstructions(CurrentUser,
                    new List<InstructionStatus> { InstructionStatus.Completed });
            return View(instructions.OrderByDescending(i => i.CreatedDate));
        }

        public IActionResult RejectedInstructions()
        {
            var instructions = _instructionService
                .GetInstructions(CurrentUser,
                    new List<InstructionStatus> { InstructionStatus.Rejected });
            return View(instructions.OrderByDescending(i => i.CreatedDate));
        }

        [HttpGet]
        public IActionResult Instruct()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Instruct(InstructionModel instruction,
            ICollection<IFormFile> UploadDocument = null)
        {
            if (ModelState.IsValid)
            {
                var documents = _documentStoreService
                    .ConvertToInstructionDocument<InstructionDocumentModel>(UploadDocument)?.ToList();
                instruction.SupportingDocuments = _mapper.Map<ICollection<InstructionDocumentModel>>(documents);
                SetNewValuerInstructionDefaults(instruction);
                await _instructionService.CreateInstruction(instruction);
                return RedirectToAction("Pending");
            }

            return View(instruction);
        }

        [HttpGet]
        public async Task<IActionResult> Accept(Guid id)
        {
            if (await CanTransact(SubscriptionType.FastTrack))
            {
                try
                {
                    await _instructionService.AcceptInstruction(CurrentUser, id);
                }
                catch (GoSmartValueException customException)
                {
                    _logger.LogError(customException, "Failed to complete the instruction acceptance process.", null);
                }

                return RedirectToAction("NewInstructions");
            }
            else
            {
                var accountId = UserAccountId().Result;
                var request = new AV.Contracts.Models.Payment.Commands.AddCreditCommand
                {
                    AccountId = accountId,
                };

                return RedirectToAction("AddCredit", "Payment", request);
            }
        }

        [HttpGet]
        public async Task<IActionResult> RejectAsync(Guid id)
        {
            if (await CanTransact(SubscriptionType.FastTrack))
            {
                var instruction = _instructionService.GetInstruction(CurrentUser, id);
                if (instruction != null && instruction.Status == InstructionStatus.New
                                        && !instruction.ValuerAccepted)
                {
                    return View(instruction);
                }

                return RedirectToAction("NewInstructions");
            }
            else
            {
                var accountId = UserAccountId().Result;
                var request = new AV.Contracts.Models.Payment.Commands.AddCreditCommand
                {
                    AccountId = accountId,
                };

                return RedirectToAction("AddCredit", "Payment", request);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Reject(InstructionModel instruction)
        {
            if (ModelState.IsValid)
            {
                await _instructionService.RejectInstruction(CurrentUser, instruction);
            }

            return RedirectToAction("NewInstructions");
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmAppointment(Guid id)
        {
            if (await CanTransact(SubscriptionType.FastTrack))
            {
                try
                {
                    await _instructionService.ConfirmInstructionAppointment(CurrentUser, id);
                    return RedirectToAction("Pending");
                }
                catch (GoSmartValueException customException)
                {
                    _logger.LogError(customException, "Failed to complete the instruction acceptance process.", null);
                }

                return RedirectToAction("NewInstructions");
            }
            else
            {
                var accountId = UserAccountId().Result;
                var request = new AV.Contracts.Models.Payment.Commands.AddCreditCommand
                {
                    AccountId = accountId,
                };

                return RedirectToAction("AddCredit", "Payment", request);
            }
        }

        public IActionResult Valuations()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BuildingInformation()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Value(Guid id)
        {
            var instruction = _instructionService.GetInstruction(CurrentUser, id);
            if (instruction == default)
            {
                throw new GoSmartValueException($"No instructions found for this Id: {id}");
            }

            if (instruction.ValuationId != null)
            {
                return RedirectToAction("ValueResultView",
                    _valuationsService.GetValuationResult(CurrentUser, instruction.Id));
            }

            ViewBag.Instruction = instruction;
            return View();
        }

        [HttpPost]
        public IActionResult Value(ValuationModel valuation, ICollection<IFormFile> Sitepictures = null)
        {
            if (ModelState.IsValid)
            {
                var documents = _documentStoreService
                    .ConvertToInstructionDocument<ValuationDocumentModel>(Sitepictures)?.ToList();
                valuation.SitePictures = _mapper.Map<ICollection<ValuationDocumentModel>>(documents);
                var valuationResult = _valuationsService.ProcessValuation(CurrentUser, valuation);
                return RedirectToAction("ValueResult", new { id = valuationResult.InstructionId });
            }

            if (valuation.Instruction == null && valuation.InstructionId != default)
            {
                var instruction = _instructionService.GetInstruction(CurrentUser, valuation.InstructionId);

                if (instruction == default)
                {
                    throw new GoSmartValueException($"No instructions found for this Id: {valuation.InstructionId}");

GoSmartValue.Web/Views/Shared/Components/Chatroom/_Post.cshtml
<div class="container">
	<div class="well">
		<div class="media">
			<a class="pull-left" href="#" style="padding:10px">
				<img class="media-object" src="/user-icon.png" height="30">
			</a>
			<div class="media-body">
				<div class="col-sm-12">
					<div class="row"><h6 class="media-heading" style="padding:10px">Market performance</h6></div>
					<div class="row col-sm-12"><span class="">By Jonathan Ditshotlo</span></div>
				</div>
				<div class="col-sm-12 container-fluid">
					<span style="font-size:14px;font-family:'Segoe UI'">
						What is your take on the impact of COVID-19 on the property market and what can be done to ensure we are all safe as valuers during this crazy times??.
					</span>
				</div>
				<div class="col-sm-12">
					<ul class="list-inline">
						<li class="list-inline-item"><span><i class="fa fa-calendar"></i> 2 hours ago </span></li>
						<li class="list-inline-item">|</li>
						<li class="list-inline-item"><a style="text-decoration:none" asp-controller="Valuer" asp-action="PostView"><i class="fa fa-comment"></i> 2 comments</a></li>
						<li class="list-inline-item">|</li>
						<li class="list-inline-item">
							<span class="fa fa-star"></span>
							<span class="fa fa-star"></span>
							<span class="fa fa-star"></span>
							<span class="fa fa-star"></span>
							<span class="fa fa-star"></span>
						</li>
					</ul>
					</div>

				</div>
			</div>
	</div>
	
</div>

GoSmartValue.Web/Views/Shared/Components/Chatroom/_PostComment.cshtml
<div class="container">
    <div class="well">
        <div class="media">
            <a class="pull-left" href="#" style="padding:10px">
                <img class="media-object" src="/user-icon.png" height="30">
            </a>
            <div class="media-body">
                <div class="col-sm-12">
                    <div class="row"><h6 class="media-heading" style="padding:10px">Market performance</h6></div>
                    <div class="row col-sm-12"><span class="">By Jonathan Ditshotlo</span></div>
                </div>
                <div class="col-sm-12 container-fluid">
                    <span style="font-size:14px;font-family:'Segoe UI'">
                        What is your take on the impact of COVID-19 on the property market and what can be done to ensure we are all safe as valuers during this crazy times??.
                    </span>
                </div>
                <div class="col-sm-12">
                    <ul class="list-inline">
                        <li class="list-inline-item"><span><i class="fa fa-calendar"></i> 2 hours ago </span></li>
                        <li class="list-inline-item">|</li>
                        <li class="list-inline-item"><span><i class="fa fa-comment"></i> 2 comments</span></li>
                        <li class="list-inline-item">|</li>
                        <li class="list-inline-item">
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </li>
                    </ul>
                </div>

                <div class="container-fluid col-sm-12 row">
                    <div class="col-sm-10"><input class="form-control" placeholder="comment..." /></div>
                    <div class="col-sm-2"><button type="submit" class="btn btn-blue">Comment</button></div>
                </div>
                <div class="media">
                    <div class="container-fluid col-sm-12 row">
                        <a class="pull-left" href="#" style="padding:10px">
                            <img class="media-object" src="/user-icon.png" height="30">
                        </a>
                        <div class="media-body">
                            <div class="col-sm-12">
                                <div class="row col-sm-12"><span class="">By Kitso Matsheng</span></div>
                            </div>
                            <div class="col-sm-12 container-fluid form-group">
                                <span style="font-size:14px;font-family:'Segoe UI'">
                                    This thing should really go away, i cant even work am losing money :((
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="media">
                    <div class="container-fluid col-sm-12 row">
                        <a class="pull-left" href="#" style="padding:10px">
                            <img class="media-object" src="/user-icon.png" height="30">
                        </a>
                        <div class="media-body">
                            <div class="col-sm-12">
                                <div class="row col-sm-12"><span class="">By Thabiso Nasha</span></div>
                            </div>
                            <div class="col-sm-12 container-fluid form-group">
                                <span style="font-size:14px;font-family:'Segoe UI'">
                                    Buckle up ladies and gentleman..looks like corona isnt going away for a while
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            </div>
    </div>

</div>