GoSmartValue.Web/Areas/admin/Controllers/ComparablesController.cs
using AutoMapper;
using AV.Common.Entities;
using AV.Contracts.Enums;
using AV.Persistence.EntityFramework;
using GoSmartValue.Web.Controllers;
using GoSmartValue.Web.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace GoSmartValue.Web.Areas.admin.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    // [Authorize(Roles = "Manager,Admin")]
    [Area("admin")]
    [Route("admin/comparables/")]
    public class ComparablesController : SecureController
    {
        private readonly ValuationsContext _context;

        public ComparablesController(
            UserManager<User> userManager,
            RoleManager<Role> roleManager,
            ValuationsContext context,
            IUserManagerService userService,
            IMapper mapper

            )
        : base(userManager, roleManager, userService, mapper)
        {
            _context = context;
        }

        [Route("Index")]
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int pageSize = 100, [FromQuery] int pageNumber = 1)
        {
            var valuationsContext = _context.Comparables
                .Where(c => c.DataState != DataState.Raw)
                .Include(p => p.Locality)
                .Include(p => p.Location)
                .Skip(pageSize * (pageNumber - 1))
                .Take(pageSize)
                .OrderByDescending(c => c.AddedOn);
            return View(await valuationsContext.ToListAsync());
        }

        // GET: admin/Comparables/Details/5
        [HttpGet]
        [Route("Details")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propertyDetail = await _context.Comparables
                .Include(p => p.Locality)
                .Include(p => p.Location)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (propertyDetail == null)
            {
                return NotFound();
            }

            return View(propertyDetail);
        }

        // GET: admin/Comparables/Create
        [HttpGet]
        [Route("Create")]
        public IActionResult Create()
        {
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "Id");
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Id");
            return View();
        }

        // POST: admin/Comparables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Create")]
        public async Task<IActionResult> Create([Bind("Id,AddedOn,DataState,DateOfSale,SalePrice,LocationId,LocalityId,StreetId,StreetName,PlotSize,PlotId,LandUse,Date,PropertyType,PlotNo")] Comparable comparable)
        {
            if (ModelState.IsValid)
            {
                comparable.Id = Guid.NewGuid();
                _context.Add(comparable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "Id", comparable.LocalityId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Id", comparable.LocationId);
            return View(comparable);
        }

        // GET: admin/Comparables/Edit/5
        [HttpGet]
        [Route("Edit")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propertyDetail = await _context.Comparables.FindAsync(id);
            if (propertyDetail == null)
            {
                return NotFound();
            }
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "Id", propertyDetail.LocalityId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Id", propertyDetail.LocationId);
            return View(propertyDetail);
        }

        // POST: admin/Comparables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Edit")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,AddedOn,DataState,DateOfSale,SalePrice,LocationId,LocalityId,StreetId,StreetName,PlotSize,PlotId,LandUse,Date,PropertyType,PlotNo")] Comparable comparable)
        {
            if (id != comparable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comparable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyDetailExists(comparable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "Id", comparable.LocalityId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Id", comparable.LocationId);
            return View(comparable);
        }

        [HttpGet("Delete")]
        // GET: admin/Comparables/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propertyDetail = await _context.Comparables
                .Include(p => p.Locality)
                .Include(p => p.Location)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (propertyDetail == null)
            {
                return NotFound();
            }

            return View(propertyDetail);
        }

        // POST: admin/Comparables/Delete/5
        [HttpPost("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var propertyDetail = await _context.Comparables.FindAsync(id);
            _context.Comparables.Remove(propertyDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropertyDetailExists(Guid id)
        {
            return _context.Comparables.Any(e => e.Id == id);
        }
    }
}

GoSmartValue.Web/Areas/admin/Views/Comparables/Create.cshtml
@model AV.Common.Entities.Comparable

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Create</h1>

<h4>Comparable details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AddedOn" class="control-label"></label>
                <input asp-for="AddedOn" class="form-control" />
                <span asp-validation-for="AddedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataState" class="control-label"></label>
                <select asp-for="DataState" class="form-control"></select>
                <span asp-validation-for="DataState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfSale" class="control-label"></label>
                <input asp-for="DateOfSale" class="form-control" />
                <span asp-validation-for="DateOfSale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalePrice" class="control-label"></label>
                <input asp-for="SalePrice" class="form-control" />
                <span asp-validation-for="SalePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class ="form-control" asp-items="ViewBag.LocationId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LocalityId" class="control-label"></label>
                <select asp-for="LocalityId" class ="form-control" asp-items="ViewBag.LocalityId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StreetId" class="control-label"></label>
                <input asp-for="StreetId" class="form-control" />
                <span asp-validation-for="StreetId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetName" class="control-label"></label>
                <input asp-for="StreetName" class="form-control" />
                <span asp-validation-for="StreetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotSize" class="control-label"></label>
                <input asp-for="PlotSize" class="form-control" />
                <span asp-validation-for="PlotSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotId" class="control-label"></label>
                <input asp-for="PlotId" class="form-control" />
                <span asp-validation-for="PlotId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LandUse" class="control-label"></label>
                <select asp-for="LandUse" class="form-control"></select>
                <span asp-validation-for="LandUse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertyType" class="control-label"></label>
                <select asp-for="PropertyType" class="form-control"></select>
                <span asp-validation-for="PropertyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotNo" class="control-label"></label>
                <input asp-for="PlotNo" class="form-control" />
                <span asp-validation-for="PlotNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoSmartValue.Web/Areas/admin/Views/Comparables/Delete.cshtml
@model AV.Common.Entities.Comparable

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comparables</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.AddedOn)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.AddedOn)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.DataState)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.DataState)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.DateOfSale)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.DateOfSale)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.SalePrice)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.SalePrice)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Location)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Location.Id)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Locality)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Locality.Id)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.StreetId)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.StreetId)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.StreetName)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.StreetName)</dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LandUse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LandUse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotNo)
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "Comparables"))
    {
        @Html.ActionLink("Delete", "Delete", "Comparables", new { @Model.Id }, new { @class = "btn btn-danger" })
        ;
        @Html.ActionLink("Back", "Index", "Comparables")
        ;
    }
    
</div>

GoSmartValue.Web/Areas/admin/Views/Comparables/Details.cshtml
@model AV.Common.Entities.Comparable

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Details</h1>
<div>
    <h4>Comparables</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfSale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfSale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalePrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locality.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LandUse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LandUse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotNo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit","Edit","Comparables", new {Id = @Model.Id}) |
    @Html.ActionLink("Back to List","Index","Comparables")
</div>

GoSmartValue.Web/Areas/admin/Views/Comparables/Edit.cshtml
@model AV.Common.Entities.Comparable

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1>Edit</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AddedOn" class="control-label"></label>
                <input asp-for="AddedOn" class="form-control" />
                <span asp-validation-for="AddedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataState" class="control-label"></label>
                <select asp-for="DataState" class="form-control"></select>
                <span asp-validation-for="DataState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfSale" class="control-label"></label>
                <input asp-for="DateOfSale" class="form-control" />
                <span asp-validation-for="DateOfSale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalePrice" class="control-label"></label>
                <input asp-for="SalePrice" class="form-control" />
                <span asp-validation-for="SalePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="ViewBag.LocationId"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityId" class="control-label"></label>
                <select asp-for="LocalityId" class="form-control" asp-items="ViewBag.LocalityId"></select>
                <span asp-validation-for="LocalityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetId" class="control-label"></label>
                <input asp-for="StreetId" class="form-control" />
                <span asp-validation-for="StreetId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetName" class="control-label"></label>
                <input asp-for="StreetName" class="form-control" />
                <span asp-validation-for="StreetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotSize" class="control-label"></label>
                <input asp-for="PlotSize" class="form-control" />
                <span asp-validation-for="PlotSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotId" class="control-label"></label>
                <input asp-for="PlotId" class="form-control" />
                <span asp-validation-for="PlotId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LandUse" class="control-label"></label>
                <select asp-for="LandUse" class="form-control"></select>
                <span asp-validation-for="LandUse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PropertyType" class="control-label"></label>
                <select asp-for="PropertyType" class="form-control"></select>
                <span asp-validation-for="PropertyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotNo" class="control-label"></label>
                <input asp-for="PlotNo" class="form-control" />
                <span asp-validation-for="PlotNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to List","Index","Comparables")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoSmartValue.Web/Areas/admin/Views/Comparables/Index.cshtml
@model IEnumerable<AV.Common.Entities.Comparable>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th cope="col">
                @Html.DisplayNameFor(model => model.DataState)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.DateOfSale)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.SalePrice)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.Locality)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.StreetName)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PlotSize)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PlotNo)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.LandUse)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PropertyType)
            </th>
            <th cope="col">
                @Html.DisplayNameFor(model => model.PlotNo)
            </th>
            <th cope="col"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <th scope="row">
            @Html.DisplayFor(modelItem => item.DataState)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfSale)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Locality.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StreetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlotSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlotNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LandUse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlotNo)
            </td>
            <td>
                @Html.ActionLink("Edit","Edit","Comparables", new {Id = @item.Id},htmlAttributes:new {@class="btn btn-success"})|
                @Html.ActionLink("Details","Details","Comparables", new {Id = @item.Id},htmlAttributes:new {@class="btn btn-primary"})|
                @Html.ActionLink("Delete","Delete","Comparables", new {Id = @item.Id},htmlAttributes:new {@class="btn btn-primary"})|
            </td>
        </tr>
}
    </tbody>
</table>